export const clothData = [
  {
    id: 'c1',
    name: 'Classic White T-Shirt',
    category: 'Men',
    price: 599,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['White', 'Black', 'Navy'],
    image: '/images/clothes/white-tshirt.jpg',
    inStock: true,
    description:
      'Soft cotton t-shirt with a classic round neck. Ideal for everyday wear.',
    tags: ['tshirt', 'casual', 'cotton'],
  },
  {
    id: 'c2',
    name: 'Slim Fit Jeans',
    category: 'Men',
    price: 1499,
    sizes: ['30', '32', '34', '36'],
    colors: ['Blue', 'Black'],
    image: '/images/clothes/slim-jeans.jpg',
    inStock: true,
    description: 'Stretchable slim fit jeans for a modern look.',
    tags: ['jeans', 'denim', 'men'],
  },
  {
    id: 'c3',
    name: 'Floral Print Dress',
    category: 'Women',
    price: 1999,
    sizes: ['S', 'M', 'L'],
    colors: ['Red', 'Pink'],
    image: '/images/clothes/floral-dress.jpg',
    inStock: true,
    description: 'Elegant floral dress with a flared hem and tie-up waist.',
    tags: ['dress', 'floral', 'women'],
  },
  {
    id: 'c4',
    name: 'Hooded Sweatshirt',
    category: 'Unisex',
    price: 1299,
    sizes: ['M', 'L', 'XL'],
    colors: ['Grey', 'Black'],
    image: '/images/clothes/hoodie.jpg',
    inStock: false,
    description: 'Cozy fleece hoodie for all-day warmth and comfort.',
    tags: ['hoodie', 'winter', 'unisex'],
  },
  {
    id: 'c5',
    name: 'Kids Cartoon T-Shirt',
    category: 'Kids',
    price: 499,
    sizes: ['4Y', '6Y', '8Y'],
    colors: ['Yellow', 'Blue'],
    image: '/images/clothes/kids-tshirt.jpg',
    inStock: true,
    description: 'Fun cartoon-printed t-shirt for kids. 100% cotton.',
    tags: ['kids', 'tshirt', 'cartoon'],
  },
  {
    id: 'c6',
    name: 'Normal t-shirt',
    category: 'Kids',
    price: 499,
    sizes: ['4Y', '6Y', '8Y'],
    colors: ['Yellow', 'Blue'],
    image: '/images/clothes/normal.jpg',
    inStock: true,
    description: 'Fun cartoon-printed t-shirt for kids. 100% cotton.',
    tags: ['kids', 'tshirt', 'cartoon'],
  },
];

export const Women = [];
export const Men = [];
export const Children = [];
